"""create

Revision ID: 11110b9399a5
Revises: 
Create Date: 2024-02-01 03:55:49.731170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11110b9399a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('investor_loan_', sa.String(), nullable=True),
    sa.Column('servicer_loan_', sa.String(), nullable=True),
    sa.Column('pool_', sa.String(), nullable=True),
    sa.Column('subpool_', sa.String(), nullable=True),
    sa.Column('distribution_date', sa.Date(), nullable=True),
    sa.Column('paid_to_date', sa.Date(), nullable=True),
    sa.Column('advance_paid_to_date', sa.Date(), nullable=True),
    sa.Column('scheduled_gross_interest', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('master_servicing_fee', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('servicing_fee', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('trustee_fee', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('insurance_fee', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('special_servicing_fee', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('scheduled_net_interest', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('other_fees', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('beginning_scheduled_balance', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('ending_scheduled_balance', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('beginning_actual__balance', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('ending_actual__balance', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('scheduled_principal', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('curtailments', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('curtailment_adjustments', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('other_principal_adjustments', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('curtailment_date', sa.Date(), nullable=True),
    sa.Column('pif_type', sa.String(), nullable=True),
    sa.Column('pif_date', sa.Date(), nullable=True),
    sa.Column('prepayment', sa.Float(), nullable=True),
    sa.Column('repurchase_principal', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('liquidation_principal', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('principal_recoveries', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('interest_recoveries', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('total_recoveries', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('principal_losses', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('interest_losses', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('total_losses', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('ppis', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('ppie', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('sscra_shorfalls', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('other_interest_adjustments', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('principal_advances', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('interest_advances', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('stop_advance_flag', sa.Boolean(), nullable=True),
    sa.Column('stop_advance_principal', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('stop_advance_interest', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('total_stop_advance', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('current_pi_constant', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('special_hazard_losses', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('fraud_losses', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('bankruptcy_losses', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('delinquency_status', sa.String(), nullable=True),
    sa.Column('reo_date', sa.Date(), nullable=True),
    sa.Column('reo_balance', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('reo_book_value', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('loan_status', sa.String(), nullable=True),
    sa.Column('neg_am', sa.Float(), nullable=True),
    sa.Column('prepay_penaltyym', sa.Float(), nullable=True),
    sa.Column('prepay_penaltyym_waived', sa.Float(), nullable=True),
    sa.Column('current_note_rate', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('next_note_rate', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('current_net_note_rate', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('next_net_note_rate', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('next_rate_adjustment_date', sa.Date(), nullable=True),
    sa.Column('next_payment_adjustment_date', sa.Date(), nullable=True),
    sa.Column('remaining_term', sa.Integer(), nullable=True),
    sa.Column('modification_flag', sa.Boolean(), nullable=True),
    sa.Column('modification_date', sa.Date(), nullable=True),
    sa.Column('beginning_deferred_balance', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('ending_deferred_balance', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('principal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total_principal_funds_available', sa.Float(), nullable=True),
    sa.Column('month', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('principal')
    op.drop_table('loan_data')
    # ### end Alembic commands ###
